# Generated by Django 3.1.4 on 2021-02-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_client', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
