# Generated by Django 3.1.4 on 2021-02-13 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('send_client', '0003_remove_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unrd', 'Unread'), ('rd', 'read '), ('answd', 'has been answered'), ('termid', 'Terminated')], default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
