# Generated by Django 3.1.4 on 2021-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_client', '0004_auto_20210216_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[(1, 'Unread'), (2, 'read '), (3, 'has been answered'), (4, 'Terminated')], default=1, max_length=6, null=True),
        ),
    ]
