# Generated by Django 3.1.4 on 2021-02-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_client', '0005_auto_20210214_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unrd', 'Unread'), ('rd', 'read '), ('answd', 'has been answered'), ('termid', 'Terminated')], default='unrd', max_length=6, null=True),
        ),
    ]
