# Generated by Django 3.1.4 on 2021-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_client', '0007_auto_20210216_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ps',
            field=models.FileField(blank=True, upload_to='Files'),
        ),
    ]
