# Generated by Django 3.1.4 on 2021-02-16 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_client', '0009_auto_20210216_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ps',
            field=models.FileField(blank=True, upload_to='protect/', validators=[django.core.validators.FileExtensionValidator()]),
        ),
    ]
